### ISSUE TITLE
Replace deprecated components in Semantic Kernel

### ISSUE THREAD

**Issue by LuisM000** [Encamina/Enmarcha#16]
In the current version of Semantic Kernel being used (1.0.0-beta8), certain elements have been identified as deprecated, such as `ISKFunction.SkillName`, `RequestSettings `or `PromptTemplateEngine`. 
This situation implies that there is a significant amount of code that should be renamed to maintain consistency and adopt best practices. 
It is proposed to review and update these deprecated elements in future releases of Semantic Kernel to ensure consistency and facilitate the transition to the latest features.

Related with https://github.com/Encamina/enmarcha/pull/15#discussion_r1410275748

**Comment by rliberoff** [comment]
The final version of SK (version 1.0.1) is already available. Let's use this version to improve and remove deprecated components.
