### ISSUE TITLE
Is version 8.0.0 generated in Debug mode?

### ISSUE THREAD

**Issue by LuisM000** [Encamina/Enmarcha#29]
The latest versions of the NuGets were generated from a branch that we merged into the main. In the pipeline, to define the build configuration, we do it like this:
https://github.com/Encamina/enmarcha/blob/a6f0d6866c6f5da1d97ce744371e7f8a8640d717/.github/workflows/main.yml#L21-L22
If I'm not mistaken (probably I am), wouldn't this cause the build to be done in Debug mode?

This is just a question, I'm not sure :)

**Comment by rliberoff** [comment]
You are not mistaken. Indeed when the CI comes from `main` is being compiled as `Debug` instead of `Release`.

I will close this issue and open a new one requesting the fix.
