### ISSUE TITLE
Deprecated Java version causing CI failure in SonarCloud task

### ISSUE THREAD

**Issue by LuisM000** [Encamina/Enmarcha#42]
### Description
As evident from the [CI run](https://github.com/Encamina/enmarcha/actions/runs/7526067398/job/20483519865?pr=41), our CI is failing due to the deprecation of the Java version (11.0.21) used for executing the SonarCloud task. This version is no longer supported.

According to [SonarSource's announcement](https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597), Java 11 support has been deprecated as of January 15th, 2024.

### Error
The error encountered is as follows:
```
The version of Java (11.0.21) used to run this analysis is deprecated, and SonarCloud no longer supports it. Please upgrade to Java 17 or later.
As a temporary measure, you can set the property 'sonar.scanner.force-deprecated-java-version' to 'true' to continue using Java 11.0.21.
This workaround will only be effective until January 28, 2024. After this date, all scans using the deprecated Java 11 will fail.
```

### Action Items
1. **Immediate Action (Temporary Measure):**
   Apply the suggested workaround by setting the 'sonar.scanner.force-deprecated-java-version' property to 'true' to allow the use of Java 11.0.21 until January 28, 2024.

2. **Long-term Solution:**
   Upgrade the Java version to Java 17 or a later supported version to ensure continued compatibility with SonarCloud.

**Comment by rliberoff** [comment]
This is related to issue #23.
