### ISSUE TITLE
Add method to delete collection at MemoryManager level in order to use the MemoryManager EventHandler. 

### ISSUE THREAD

**Issue by VictorMuMo** [Encamina/Enmarcha#65]
The method `RemoveOutdatedCollectionAsync` in the `EphemeralMemoryStoreHandler`  class calls the method  `DeleteCollectionAsync` from the `MemoryStore` class that deletes an entire collection using the name of the collection. As the method is inside the `MemoryStore` object the event of deleting a collection is not getting raised at the `MemoryManager` level and would be good to take advantage of the `EventHandler` that the class already has. That's what we are proposing to create a method to delete a collection at the MemoryManager level.

**Comment by fjbelizon** [comment]
I totally agree, this is a problem to be solved. The event handler managed by `MemoryManager` cannot know if a deletion has been made if the `MemoryStore` object is used directly. The correct thing to do is to have the `MemoryManager` object handle the deletion of collections and handle the associated event.
