### ISSUE TITLE
Handling Http NotFound Exception in MemoryStoreExtender

### ISSUE THREAD

**Issue by LuisM000** [Encamina/Enmarcha#72]
**Description:**

**Problem:**
When attempting to retrieve a memory from the MemoryStore using `MemoryStore.GetAsync`, the current implementation encounters an issue specific to the Azure AI Search Memory Store. In this scenario, if the requested element does not exist, instead of returning a null value as expected, the method throws a `RequestFailedException` with a status code of Http NotFound (404).

**Current Solution:**
To address this issue, a try-catch block has been implemented to catch the `RequestFailedException` with a specific check for Http NotFound status. This prevents the exception from propagating further and allows the program to continue execution without disruption.

**Reasoning:**
The try-catch block is a temporary solution to handle the unexpected behavior of the MemoryStore in the Azure AI Search context. Ideally, the `MemoryStore.GetAsync` method should return null when the requested element is not found, eliminating the need for exception handling in this case.

**Solution:**
An issue has been opened in Semantic Kernel to address the root cause of this behavior. Once this issue in Semantic Kernel is resolved and our code is updated to the version of Semantic Kernel that includes the fix, we should remove the try-catch block associated with this temporary workaround.

**Issue Link:**
[Link to Semantic Kernel Issue](https://github.com/microsoft/semantic-kernel/issues/4952)

**Comment by rliberoff** [comment]
This is being reported to Semantic Kernel (SK) with issue [4952](https://github.com/microsoft/semantic-kernel/issues/4952).

Also, it seems to be fixed in PR [4992](https://github.com/microsoft/semantic-kernel/pull/4992).

It is expected to be solved in their next release.

**Comment by LuisM000** [comment]
A new version of Semantic Kernel ([v.1.4.0](https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-1.4.0)) with the fix has been released🎉
